#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v3

documentation:
  - title: mod-finance-storage (Budgets)
    content: <b>CRUD APIs used to manage budgets.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  budget: !include acq-models/mod-finance/schemas/budget.json
  budget-collection: !include acq-models/mod-finance/schemas/budget_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/budgets:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/budget_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/budget.sample
      schemaCollection: budget-collection
      schemaItem: budget
  is: [validate]
  get:
    description: Get list of budgets
    is: [
      searchable: {description: "with valid searchable fields: e.g.", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a budget
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/budget.sample
        schema: budget
    is: [validate]

