#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Budgets)
    content: <b>CRUD APIs used to manage budgets.</b>

schemas:
  - budget.json: !include schemas/budget.json
  - budget_collection: !include schemas/budget_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/budget:
  type:
    collection:
      exampleCollection: !include examples/budget_collection.sample
      exampleItem: !include examples/budget.sample
      schemaCollection: budget_collection
      schemaItem: budget.json
  get:
    description: Get list of budgets
    is: [
      searchable: {description: "with valid searchable fields: e.g.", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/budget.sample
        schema: budget.json
