#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage (Budget expense classes)
    content: <b>CRUD APIs used to manage budget-expense-class records.</b>

types:
  expenseClassStatus: !include acq-models/mod-finance/schemas/expense_class_status.json
  errors: !include raml-util/schemas/errors.schema
  budget-expense-class: !include acq-models/mod-finance/schemas/budget_expense_class.json
  budget-expense-class-collection: !include acq-models/mod-finance/schemas/budget_expense_class_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/budget-expense-classes:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/budget_expense_class_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/budget_expense_class.sample
      schemaCollection: budget-expense-class-collection
      schemaItem: budget-expense-class
  is: [validate]
  get:
    description: Get list of budget-expense-classes
    is: [
      searchable: {description: "with valid searchable fields: e.g.", example: "[\"name\", \"Electronic\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a budget-expense-class
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/budget_expense_class.sample
        schema: budget-expense-class
    is: [validate]
