#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v2

documentation:
  - title: mod-finance-storage (Encumbrance)
    content: <b>CRUD APIs used to manage encumbrances.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  encumbranceTransaction: !include acq-models/mod-finance/schemas/transaction.json
  encumbranceTransaction_collection: !include acq-models/mod-finance/schemas/transaction_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/encumbrances:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/transaction_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/transaction.sample
      schemaCollection: encumbranceTransaction_collection
      schemaItem: encumbranceTransaction
  is: [validate]
  get:
    description: Get list of encumbrances
    is: [
      searchable: {description: "with valid searchable fields: e.g.", example: "[\"status\", \"Unreleased\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of an encumbrance
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/transaction.sample
        schema: encumbranceTransaction
    is: [validate]
