#%RAML 1.0
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Budgets)
    content: <b>CRUD APIs used to manage encumbrances.</b>

types:
  encumbrance: !include acq-models/mod-finance/schemas/encumbrance.json
  encumbrance_collection: !include acq-models/mod-finance/schemas/encumbrance_collection.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/encumbrance:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/encumbrance_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/encumbrance.sample
      schemaCollection: encumbrance_collection
      schemaItem: encumbrance
  get:
    description: Get list of encumbrances
    is: [
      searchable: {description: "with valid searchable fields: e.g.", example: "[\"status\", \"Unreleased\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/encumbrance.sample
        schema: encumbrance
