#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage
    content: <b>CRUD APIs used to manage miscellaneous APIs.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  ledgerFY-collection: !include acq-models/mod-finance/schemas/ledgerFY_collection.json

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml


/finance-storage:
 /ledger-fiscal-years:
   get:
      displayName: ledger FiscalYear
      description: Get the ledger for a given fiscal year
      is: [
       pageable,
       searchable: {
        description:
          "With valid searchable fields",
        example:
          "ledger.name==Main AND allocated==200 sortBy currency"
       },
       validate
      ]
   type:
      collection-get:
        exampleCollection: !include acq-models/mod-finance/examples/ledgerFY_collection.sample
        schemaCollection: ledgerFY-collection
