#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Fiscal Year)
    content: <b>CRUD APIs used to manage fiscal years.</b>

schemas:
  - fiscal_year.json: !include schemas/fiscal_year.json
  - fiscal_year_collection: !include schemas/fiscal_year_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/fiscal_year:
  type:
    collection:
      exampleCollection: !include examples/fiscal_year_collection.sample
      exampleItem: !include examples/fiscal_year.sample
      schemaCollection: fiscal_year_collection
      schemaItem: fiscal_year.json
  get:
    description: Get list of fiscal years
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/fiscal_year.sample
        schema: fiscal_year.json
