#%RAML 1.0
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Fund Distributions)
    content: <b>CRUD APIs used to manage fund-distributions.</b>

types:
  fund_distribution: !include acq-models/mod-finance/schemas/fund_distribution.json
  fund_distribution_collection: !include acq-models/mod-finance/schemas/fund_distribution_collection.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/fund_distribution:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/fund_distribution_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/fund_distribution.sample
      schemaCollection: fund_distribution_collection
      schemaItem: fund_distribution
  get:
    description: Get list of fund distributions
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/fund_distribution.sample
        schema: fund_distribution
