#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Fund Distributions)
    content: <b>CRUD APIs used to manage fund-distributions.</b>

schemas:
  - fund_distribution.json: !include schemas/fund_distribution.json
  - fund_distribution_collection: !include schemas/fund_distribution_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/fund_distribution:
  type:
    collection:
      exampleCollection: !include examples/fund_distribution_collection.sample
      exampleItem: !include examples/fund_distribution.sample
      schemaCollection: fund_distribution_collection
      schemaItem: fund_distribution.json
  get:
    description: Get list of fund distributions
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/fund_distribution.sample
        schema: fund_distribution.json
