#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage (Funds)
    content: <b>CRUD APIs used to manage funds.</b>

types:
  fund: !include acq-models/mod-finance/schemas/fund.json
  fund_collection: !include acq-models/mod-finance/schemas/fund_collection.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/fund:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/fund_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/fund.sample
      schemaCollection: fund_collection
      schemaItem: fund
  get:
    description: Get list of funds
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/fund.sample
        schema: fund
