#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Ledgers)
    content: <b>CRUD APIs used to manage ledgers.</b>

schemas:
  - ledger.json: !include schemas/ledger.json
  - ledger_collection: !include schemas/ledger_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/ledger:
  type:
    collection:
      exampleCollection: !include examples/ledger_collection.sample
      exampleItem: !include examples/ledger.sample
      schemaCollection: ledger_collection
      schemaItem: ledger.json
  get:
    description: Get list of ledgers
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/ledger.sample
        schema: ledger.json
