#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage (Ledgers)
    content: <b>CRUD APIs used to manage ledgers.</b>

types:
  ledger: !include acq-models/mod-finance/schemas/ledger.json
  ledger_collection: !include acq-models/mod-finance/schemas/ledger_collection.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/ledger:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/ledger_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/ledger.sample
      schemaCollection: ledger_collection
      schemaItem: ledger
  get:
    description: Get list of ledgers
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/ledger.sample
        schema: ledger
