#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Tags)
    content: <b>CRUD APIs used to manage tags.</b>

schemas:
  - tag.json: !include schemas/tag.json
  - tag_collection: !include schemas/tag_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/tag:
  type:
    collection:
      exampleCollection: !include examples/tag_collection.sample
      exampleItem: !include examples/tag.sample
      schemaCollection: tag_collection
      schemaItem: tag.json
  get:
    description: Get list of tags
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/tag.sample
        schema: tag.json
