#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage (Transaction summaries)
    content: <b>CRUD APIs used to manage transaction summaries.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  order-transaction-summary: !include acq-models/mod-finance/schemas/order_transaction_summary.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  get-delete: !include raml-util/rtypes/get-delete.raml

/finance-storage/order-transaction-summaries:
  post:
    description: Create a new order transaction summary item.
    body:
      application/json:
        type: order-transaction-summary
        example:
          strict: false
          value: !include acq-models/mod-finance/examples/order_transaction_summary.sample
    responses:
      201:
        description: "Returns a newly created item, with server-controlled fields like 'id' populated"
        headers:
          Location:
            description: URI to the created order transaction summary item
        body:
          application/json:
            example: !include acq-models/mod-finance/examples/order_transaction_summary.sample
      400:
        description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
        body:
          text/plain:
            example: |
              "unable to add order transaction summary -- malformed JSON at 13:3"
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
            example: "unable to create order transaction summary record -- unauthorized"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  is: [validate]

  /{id}:
    uriParameters:
      id:
        description: The UUID of an order transaction summary
        type: UUID
    type:
      get-delete:
        exampleItem: !include acq-models/mod-finance/examples/order_transaction_summary.sample
        schema: order-transaction-summary
    is: [validate]
