#%RAML 1.0
title: "mod-finance-storage"
baseUri: https://github.com/folio-org/mod-finance-storage
version: v1

documentation:
  - title: mod-finance-storage (Transactions)
    content: <b>CRUD APIs used to manage transactions.</b>

types:
  transaction: !include acq-models/mod-finance/schemas/transaction.json
  transaction_collection: !include acq-models/mod-finance/schemas/transaction_collection.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance-storage/transaction:
  type:
    collection:
      exampleCollection: !include acq-models/mod-finance/examples/transaction_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/transaction.sample
      schemaCollection: transaction_collection
      schemaItem: transaction
  get:
    description: Get list of transactions
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-finance/examples/transaction.sample
        schema: transaction
