#%RAML 0.8
title: "mod-funds"
baseUri: https://github.com/folio-org/mod-funds
version: v1

documentation:
  - title: mod-funds (Transactions)
    content: <b>CRUD APIs used to manage transactions.</b>

schemas:
  - transaction.json: !include schemas/transaction.json
  - transaction_collection: !include schemas/transaction_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/transaction:
  type:
    collection:
      exampleCollection: !include examples/transaction_collection.sample
      exampleItem: !include examples/transaction.sample
      schemaCollection: transaction_collection
      schemaItem: transaction.json
  get:
    description: Get list of transactions
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/transaction.sample
        schema: transaction.json
